# File           : README.org
# Created        : <2016-11-16 Wed 00:51:06 GMT>
# Last Modified  : <2016-12-21 Wed 21:24:00 GMT> sharlatan
# Author         : sharlatan
# Maintainer(s)  :
# Short          :

#+OPTIONS: num:nil

Collection of templates which I came across during daily work and research
Internet for the "Answer". It a consolidated experience of using *nix OSes

Contribution welcome!

[[./cix-main.org][cix-main]]

** Structure

- cix-main.org :: Index of of all files.
- img/ :: Picture files.
- spices/ :: Collection of files stuffed with examples.
- tests/ :: Files for testing referenced in examples.
- tutors/ :: Full size tutorials "How to"

** Layout
I use org-mode format for example files. It's a very powerful and flexible but
takes time to master it.

Style requirements for exampls

Variables
#+BEGIN_EXAMPLE
VAR_STRING="string"
VAR_NUM=1234
VAR_PATH="/path/to/somewhere"
#+END_EXAMPLE

Structure

#+BEGIN_EXAMPLE
Package name

| Author      | |
| Maintainers | |
| Released    | |
| Source      | |
| Info        | |

Long discription

* Index
List of commands inluded in package with shor description
* Receipts
** command
*** command::options
*** command::examples
*** command::files
*** command::see-also
* References
** Books
** Links
** Wiki
** IRC
#+END_EXAMPLE

Example header with time-stamp
- command-YmdHMS :: short description:
#+BEGIN_SRC sh
  #!/usr/bin/env sh
  # Point to what shell did you use.

  # Body, less word more examples!
#+END_SRC
cmd (1) link to other command used

** Convert to whatever
Export *org files to {pdf,html,tex,txt,whatever}
- Emacs Org-Mode http://orgmode.org/manual/Exporting.html
- Pandoc http://pandoc.org/demos.html
- Org to Reveal.js https://github.com/yjwen/org-reveal
- Org to nice HTML https://github.com/fniessen/org-html-themes
