# File           : cix-ctags.org
# Created        : <2017-08-15 Tue 22:44:20 BST>
# Modified       : <2017-9-04 Mon 22:42:28 BST> sharlatan
# Author         : sharlatan
# Maintainer(s)  :
# Sinopsis       : A C programming language indexing and/or cross-reference tool.

#+OPTIONS: num:nil

[[file:../README.org*Index][|≣|]]
#+TITLE: ctags
|-----------------+-------------------|
| *Author(s)*     | Ken Arnold        |
|                 | Darren Hiebert,   |
|                 | David Fishburn,   |
|                 | Dmitri Tikhonov,  |
|                 | Elias Pschernig,  |
|                 | Elliott Hughes,   |
|                 | John Lindal,      |
|                 | Joseph Koshy,     |
|                 | Vincent Berthoux, |
| *Maintainer(s)* | Reza Jelveh       |
| *Released*      | 1987,             |
|                 | 1996              |
| *Source*        | [[https://github.com/universal-ctags/ctags][ctags.git]],        |
|                 | [[http://ctags.sourceforge.net/][ctags.web]],        |
|                 | [[http://bxr.su/FreeBSD/usr.bin/ctags/][ctags.web]]         |
| *Info*          | [[https://ctags.io/][ctagas.web]]        |
|-----------------+-------------------|

Ctags generates an index (or tag) file of C language objects found in C source
and header files. The index makes it easy for text editors or other utilities to
locate the indexed items. Ctags can also generate a cross reference file which
lists information about the various objects found in a set of C language files
in human readable form. Exuberant Ctags improves on ctags because it can find
all types of C language tags, including macro definitions, enumerated values
(values inside enum{...}), function and method definitions, enum/struct/union
tags, external function prototypes, typedef names and variable declarations.
Exuberant Ctags is far less likely to be fooled by code containing #if
preprocessor conditional constructs than ctags. Exuberant ctags supports output
of Emacs style TAGS files and can be used to print out a list of selected
objects found in source files.
-----
* Index
* Receipts
* Refreances

# End of cix-ctags.org
