# File          : gnu-core-utilities.md
# Created       : Wed 14 Oct 2015 23:07:41
# Last Modified : <2016-11-21 Mon 01:05:12 GMT> sharlatan
# Maintainer    : sharlatan

#+OPTIONS: num:nil

[[../README.org::*Index][|≣|]][[https://www.gnu.org/software/coreutils/coreutils.html][|↷|]]

#+TITLE: GNU Core Utilities

|-------------+---------------|
| *Author*      |               |
|-------------+---------------|
| *Maintainers* |               |
| *Realised*    |               |
| *Source*      | [[http://git.savannah.gnu.org/cgit/coreutils.git][coreutils.git]] |
| *Info*        | [[http://www.gnu.org/software/coreutils/manual/coreutils.html][GNU Coreutils]] |
|-------------+---------------|

The GNU Core Utilities are the basic file, shell and text manipulation
utilities of the  GNU operating system.  These are  the core utilities
which are expected  to exist on every operating  system.  This package
is the union of the GNU fileutils, sh-utils, and textutils packages.
-----

* Index
#+BEGIN_EXAMPLE
    cp (1)        - copy files and directories
    dd (1)        - convert and copy a file
    df (1)        - report file system disk space usage
    du (1)        - estimate file space usage
    id (1)        - print real and effective user and group IDs
    ln (1)        - make links between files
    ls (1)        - list directory contents
    mv (1)        - move (rename) files
    nl (1)        - number lines of files
    od (1)        - dump files in octal and other formats
    pr (1)        - convert text files for printing
    rm (1)        - remove files or directories
    tr (1)        - translate or delete characters
    wc (1)        - print newline, word, and byte counts for each file

    cat (1)       - concatenate files and print on the standard output
    cut (1)       - remove sections from each line of files
    dir (1)       - list directory contents
    env (1)       - run a program in a modified environment
    fmt (1)       - simple optimal text formatter
    ptx (1)       - produce a permuted index of file contents
    pwd (1)       - print name of current/working directory
    seq (1)       - print a sequence of numbers
    sum (1)       - checksum and count the blocks in a file
    tac (1)       - concatenate and print files in reverse
    tee (1)       - read from standard input and write to standard output and files
    tty (1)       - print the file name of the terminal connected to standard input
    who (1)       - show who is logged on
    yes (1)       - output a string repeatedly until killed

    arch (1)      - print machine hardware name (same as uname - m)
    comm (1)      - compare two sorted files line by line
    date (1)      - print or set the system date and time
    echo (1)      - display a line of text
    expr (1)      - evaluate expressions
    fold (1)      - wrap each input line to fit in specified width
    head (1)      - output the first part of files
    join (1)      - join lines of two files on a common field
    link (1)      - call the link function to create a link to a file
    nice (1)      - run a program with modified scheduling priority
    shuf (1)      - generate random permutations
    sort (1)      - sort lines of text files
    stat (1)      - display file or file system status
    stty (1)      - change and print terminal line settings
    sync (1)      - flush file system buffers
    tail (1)      - output the last part of files
    test (1)      - check file types and compare values
    true (1)      - do nothing, successfully
    uniq (1)      - report or omit repeated lines
    vdir (1)      - list directory contents

    chcon (1)     - change file SELinux security context
    chgrp (1)     - change group ownership
    chmod (1)     - change file mode bits
    chown (1)     - change file owner and group
    cksum (1)     - checksum and count the bytes in a file
    false (1)     - do nothing, unsuccessfully
    mkdir (1)     - make directories
    mknod (1)     - make block or character special files
    nohup (1)     - run a command immune to hangups, with output to a non-tty
    nproc (1)     - print the number of processing units available
    paste (1)     - merge lines of files
    pinky (1)     - lightweight finger
    rmdir (1)     - remove empty directories
    shred (1)     - overwrite a file to hide its contents, and optionally delete it
    sleep (1)     - delay for a specified amount of time
    split (1)     - split a file into pieces
    touch (1)     - change file timestamps
    tsort (1)     - perform topological sort
    uname (1)     - print system information
    users (1)     - print the user names of users currently logged in to the current host

    base64 (1)    - base64 encode/decode data and print to standard output
    chroot (1)    - run command or interactive shell with special root directory
    csplit (1)    - split a file into sections determined by context lines
    expand (1)    - convert tabs to spaces
    factor (1)    - factor numbers
    groups (1)    - print the groups a user is in
    hostid (1)    - print the numeric identifier for the current host
    md5sum (1)    - compute and check MD5 message digest
    mkfifo (1)    - make FIFOs (named pipes)
    mktemp (1)    - create a temporary file or directory
    numfmt (1)    - Convert numbers from/to huma-readable strings
    printf (1)    - format and print data
    runcon (1)    - run command with specified SELinux security context
    stdbuf (1)    - Run COMMAND, with modified buffering operations for its standard streams.
    unlink (1)    - call the unlink function to remove the specified file
    uptime (1)    - Tell how long the system has been running.
    whoami (1)    - print effective userid

    dirname (1)   - strip last component from file name
    install (1)   - copy files and set attributes
    logname (1)   - print user's login name
    pathchk (1)   - check whether file names are valid or portable
    sha1sum (1)   - compute and check SHA1 message digest
    timeout (1)   - run a command with a time limit

    basename (1)  - strip directory and suffix from filenames
    printenv (1)  - print all or part of environment
    readlink (1)  - print resolved symbolic links or canonical file names
    realpath (1)  - print the resolved path
    realpath (3)  - return the canonicalized absolute pathname
    truncate (1)  - shrink or extend the size of a file to the specified size
    unexpand (1)  - convert spaces to tabs

    dircolors (1) - color setup for ls
    sha224sum (1) - compute and check SHA224 message digest
    sha256sum (1) - compute and check SHA256 message digest
    sha384sum (1) - compute and check SHA384 message digest
    sha512sum (1) - compute and check SHA512 message digest
#+END_EXAMPLE
-----

* Receipts
** arch                                                                         :cmd:
[[Index][⬆]]
*** arch::options
*** arch::examples
*** arch::files
*** arch::see-also
** base64                                                                       :cmd:
[[Index][⬆]] /base64 encode/decode data and print to standard output/
/Written by Simon Josefsson/
*** base64::options
*** base64::examples
- base64-161121003148 :: create a *C* chars by *N* lines file of random ASCII:
#+BEGIN_SRC sh
  #!/usr/bin/env bash

  ABSPATH="$(dirname $(readlink -f $0))"

  L=100
  C=80
  FILE_PATH="$ABSPATH"/../tests/rnd"$C"x"$L"

  if [ -e "$FILE_PATH" ]; then
      rm "$FILE_PATH"
  fi

  for ((n=0;n<"$L";n++)); do
      base64 /dev/urandom | head -c "$C" >> "$FILE_PATH"
  done
#+END_SRC
[[file:./cix-gnu-bash-builtin.org::*if][if]],
[[file:./cix-gnu-bash-builtin.org::*for][for]],
[[file:./cix-gnu-core-utilities.org::*dirname][dirname (1)]],
[[file:./cix-gnu-core-utilities.org::*readlink][readlink (1)]],
[[file:./cix-gnu-core-utilities.org::*rm][rm (1)]],
[[file:./cix-gnu-core-utilities.org::*head][head (1)]],


*** base64::files
*** base64::see-also
** basename                                                                     :cmd:
[[Index][⬆]]
*** basename::options
*** basename::examples
*** basename::files
*** basename::see-also
** cat                                                                          :cmd:
[[Index][⬆]]
*** cat::options
*** cat::examples
*** cat::files
*** cat::see-also
** chcon                                                                        :cmd:
[[Index][⬆]]
*** chcon::options
*** chcon::examples
*** chcon::files
*** chcon::see-also
** chgrp                                                                        :cmd:
[[Index][⬆]]
*** chgrp::options
*** chgrp::examples
*** chgrp::files
*** chgrp::see-also
** chmod                                                                        :cmd:
[[Index][⬆]] /change file mode bits/
/Written by David MacKenzie and Jim Meyering/

*** chmod::options
/[ugoa+-=rwxXstA]/
/[{1,7}{1,7}{1,7}]/

*** chmod::examples
*** chmod::files
*** chmod::see-also
** chown                                                                        :cmd:
[[Index][⬆]]
*** chown::options
*** chown::examples
*** chown::files
*** chown::see-also
** chroot                                                                       :cmd:
[[Index][⬆]]
*** chroot::options
*** chroot::examples
*** chroot::files
*** chroot::see-also
** cksum                                                                        :cmd:
[[Index][⬆]]
*** cksum::options
*** cksum::examples
*** cksum::files
*** cksum::see-also
** comm                                                                         :cmd:
[[Index][⬆]]
*** comm::options
*** comm::examples
*** comm::files
*** comm::see-also
** cp                                                                           :cmd:
[[Index][⬆]]
*** cp::options
*** cp::examples
*** cp::files
*** cp::see-also
** csplit                                                                       :cmd:
[[Index][⬆]]
*** csplit::options
*** csplit::examples
*** csplit::files
*** csplit::see-also
** cut                                                                          :cmd:
[[Index][⬆]]
*** cut::options
*** cut::examples
*** cut::files
*** cut::see-also
** date                                                                         :cmd:
[[Index][⬆]]
*** date::options
*** date::examples
*** date::files
*** date::see-also
** dd                                                                           :cmd:
[[Index][⬆]] /convert and copy a file/
/Written by Paul Rubin, David MacKenzie, and Stuart Kemp./

*** dd::options

|--------------+---|
| bs=BYTES     |   |
| cbs=BYTES    |   |
| conv=CONVS   |   |
| count=N      |   |
| ibs=BYTES    |   |
| if=FILE      |   |
| iflag=FLAGS  |   |
| obs=BYTES    |   |
| of=FILE      |   |
| oflag=FLAGS  |   |
| seek=N       |   |
| skip=N       |   |
| status=LEVEL |   |
|--------------+---|

*** dd::examples

- dd-161116230224 :: Memory I/O speed test.
: time dd if=/dev/zero of=/dev/null bs=1M count=32768

- dd-161113185213 :: Test NFS, LAN and I/O speed
#+BEGIN_SRC sh
  #!/usr/bin/bash

  NFS_PATH="/mount/point/of/nfs/dir"
  echo "Write speed"
  time dd if=/dev/zero of="$NFS_PATH"/test_file bs=16k count=16384

  echo "Read speed"
  time dd if="$NFS_PATH"/test_file of=/dev/null bs=16k
#+END_SRC
[[./cix-gnu-bash-builtin.org::echo][echo]]

- dd-161113185234 :: Copy and restore MBR of block device (HDD/SSD).
#+BEGIN_SRC sh
  #!/usr/bin/bash

  BLK_CP="/dev/sda"
  BLK_RS="/dev/sdb"
  MBR="$HOME"/mbr.img

  echo "Copy MBR data from $BLK_CP"
  dd if="$BLK_CP" of="$MBR" bs=512 count=1
  echo "Restore MBR data to $BLK_RS"
  dd if="$MBR" of="$BLK_RS"
#+END_SRC
[[./cix-gnu-bash-builtin.org::echo][echo]]

- dd-161113185337 :: Stress test of BLOCK device with random size files to a random sector number.
     WARRNING: IT COULD DAMAGE YOUR DEVICE!
#+BEGIN_SRC sh
  #!/usr/bin/bash

  MNT_PATH="/mnt/lv_test"
  DEV_NAME="sdc"
  DEV_SIZE=$(cat "/sys/block/$DEV_NAME/size")
  MBR=512

  while true; do
      SECTOR="$(shuf -i"$MBR"-"$DEV_SIZE" -n1)"
      LENGTH="$(shuf -i"$SECTOR"-"$DEV_SIZE" -n1)"

      # write to DEV
      dd if=/dev/urandom \
         of="$MNT_PATH"/file_name \
         seek="$SECTOR" \
         count="$LENGTH"b 1>/dev/null

      # read from DEV
      dd if="$MNT_PATH"/file_name of=/dev/null 1>/dev/null

      # clean up and loop
      rm "$MNT_PATH"/file_name
  done
#+END_SRC
[[./cix-gnu-core-utilities.org::*shuf][shuf (1)]],
[[file:./cix-gnu-core-utilities.org::*rm][rm (1)]],
[[./cix-gnu-core-utilities.org::*cat][cat (1)]]
[[./cix-gnu-bash-builtin.org::*while][while]],

- dd-161115233028 :: Dublicte several drives cuncurrently.
#+BEGIN_SRC sh
  #!/usr/bin/env bash

  DEV_1="/dev/sda"
  DEV_2="/dev/sdb"
  DEV_3="/dev/sdc"
  DEV_4="/dev/sdd"

  # Add as many as needed afte tee command
  dd if="$DEV_1" bs=64k \
      | tee >(dd of="$DEV_2" bs=64k) \
            >(dd of="$DEV_3" bs=64k) \
      | dd of="$DEV_4" bs=64k
#+END_SRC
[[file:./cix-gnu-core-utilities.org::*tee][tee (1)]],
*** dd::files
*** dd::see-also
** df                                                                           :cmd:
[[Index][⬆]]
*** df::options
*** df::examples
*** df::files
*** df::see-also
** dir                                                                          :cmd:
[[Index][⬆]]
*** dir::options
*** dir::examples
*** dir::files
*** dir::see-also
** dircolors                                                                    :cmd:
[[Index][⬆]]
*** dircolors::options
*** dircolors::examples
*** dircolors::files
*** dircolors::see-also
** dirname                                                                      :cmd:
[[Index][⬆]]
*** dirname::options
*** dirname::examples
*** dirname::files
*** dirname::see-also
** du                                                                           :cmd:
[[Index][⬆]]
*** du::options
*** du::examples
*** du::files
*** du::see-also
** echo                                                                         :cmd:
[[Index][⬆]]
*** echo::options
*** echo::examples
*** echo::files
*** echo::see-also
** env                                                                          :cmd:
[[Index][⬆]]
*** env::options
*** env::examples
*** env::files
*** env::see-also
** expand                                                                       :cmd:
[[Index][⬆]]
*** expand::options
*** expand::examples
*** expand::files
*** expand::see-also
** expr                                                                         :cmd:
[[Index][⬆]]
*** expr::options
*** expr::examples
*** expr::files
*** expr::see-also
** factor                                                                       :cmd:
[[Index][⬆]]
*** factor::options
*** factor::examples
*** factor::files
*** factor::see-also
** false                                                                        :cmd:
[[Index][⬆]]
*** false::options
*** false::examples
*** false::files
*** false::see-also
** fmt                                                                          :cmd:
[[Index][⬆]]
*** fmt::options
*** fmt::examples
*** fmt::files
*** fmt::see-also
** fold                                                                         :cmd:
[[Index][⬆]]
*** fold::options
*** fold::examples
*** fold::files
*** fold::see-also
** groups                                                                       :cmd:
[[Index][⬆]]
*** groups::options
*** groups::examples
*** groups::files
*** groups::see-also
** head                                                                         :cmd:
[[Index][⬆]]
*** head::options
*** head::examples
*** head::files
*** head::see-also
** hostid                                                                       :cmd:
[[Index][⬆]]
*** hostid::options
*** hostid::examples
*** hostid::files
*** hostid::see-also
** id                                                                           :cmd:
[[Index][⬆]]
*** id::options
*** id::examples
*** id::files
*** id::see-also
** install                                                                      :cmd:
[[Index][⬆]]
*** install::options
*** install::examples
*** install::files
*** install::see-also
** join                                                                         :cmd:
[[Index][⬆]]
*** join::options
*** join::examples
*** join::files
*** join::see-also
** link                                                                         :cmd:
[[Index][⬆]]
*** link::options
*** link::examples
*** link::files
*** link::see-also
** ln                                                                           :cmd:
[[Index][⬆]]
*** ln::options
*** ln::examples
*** ln::files
*** ln::see-also
** logname                                                                      :cmd:
[[Index][⬆]]
*** logname::options
*** logname::examples
*** logname::files
*** logname::see-also
** ls                                                                           :cmd:
[[Index][⬆]]
*** ls::options

: ls [-aAlbBCdDfFghHiIklLmNopqQrRsStTuvwxXZ1] [FILE/DIRECTORY]
*** ls::examples
- ls-161118234510 :: Tree view of all sub directories.
#+BEGIN_SRC sh
  #!/usr/bin/env bash

  ls -R \
      | grep ":$" \
      | sed -e 's/:$//' \
            -e 's/[^-][^\/]*\//--/g' \
            -e 's/^/   /' \
            -e 's/-/|/'
#+END_SRC
[[file:./cix-gnu-grep.org::*grep][grep (1)]],
sed (1)
- ls-161107232103 :: Sweet examples of using *ls*
#+BEGIN_EXAMPLE
    $: ls -Rotti
    $: ls -Ham
    $: ls -and
    $: ls -alSh
#+END_EXAMPLE

- ls-161107232114 :: List only: Dir, files, links; hidden dirs, hidden files
     hidden links,exec files. Actively using -F key to classify */=>@|
#+BEGIN_EXAMPLE
    $: ls -F | grep '/' | cut -d/ -f1
    $: ls -p | grep -v /
    $: ls -F | grep '[@]' | cut -d@ -f1
#+END_EXAMPLE

- ls-151114230741 :: Aliases best practice.
#+BEGIN_EXAMPLE
    alias ls="ls -1p --color=auto"
    alias l="ls -lhGgo"
    alias ll="ls -lh"
    alias la="ls -lhGgoA"
    alias lt="ls -lhGgotr"
    alias lS="ls -lhGgoSr"
    alias l.="ls -lhGgod .*"
    alias lhead="ls -lhGgo | head"
    alias ltail="ls -lhGgo | tail"
    alias lmore='ls -lhGgo | more'
#+END_EXAMPLE
*** ls::see-also
  dir (1),
** md5sum                                                                       :cmd:
[[Index][⬆]]
*** md5sum::options
*** md5sum::examples
*** md5sum::files
*** md5sum::see-also
** mkdir                                                                        :cmd:
[[Index][⬆]] /make directories/
/Written by David MacKenzie/
*** mkdir::options
*** mkdir::examples
- mkdir-161120111806 :: create a set of 135199 directories:
:    ~$ mkdir ./test_dir{1..1}{a..z}{A..Z}
*** mkdir::files
*** mkdir::see-also
** mkfifo                                                                       :cmd:
[[Index][⬆]]
*** mkfifo::options
*** mkfifo::examples
*** mkfifo::files
*** mkfifo::see-also
** mknod                                                                        :cmd:
[[Index][⬆]]
*** mknod::options
*** mknod::examples
*** mknod::files
*** mknod::see-also
** mktemp                                                                       :cmd:
[[Index][⬆]]
*** mktemp::options
*** mktemp::examples
*** mktemp::files
*** mktemp::see-also
** mv                                                                           :cmd:
[[Index][⬆]] /move (rename) files/
/Written by Mike Parker, David MacKenzie, and Jim Meyering./
*** mv::options
*** mv::examples
*** mv::files
*** mv::see-also
  [[file:./cix-util-linux.org::*rename][rename(2)]]
** nice                                                                         :cmd:
[[Index][⬆]]
*** nice::options
*** nice::examples
*** nice::files
*** nice::see-also
** nl                                                                           :cmd:
[[Index][⬆]]
*** nl::options
*** nl::examples
*** nl::files
*** nl::see-also
** nohup                                                                        :cmd:
[[Index][⬆]]
*** nohup::options
*** nohup::examples
*** nohup::files
*** nohup::see-also
** nproc                                                                        :cmd:
[[Index][⬆]]
*** nproc::options
*** nproc::examples
*** nproc::files
*** nproc::see-also
** numfmt                                                                       :cmd:
[[Index][⬆]]
*** numfmt::options
*** numfmt::examples
*** numfmt::files
*** numfmt::see-also
** od                                                                           :cmd:
[[Index][⬆]]
*** od::options
*** od::examples
*** od::files
*** od::see-also
** paste                                                                        :cmd:
[[Index][⬆]]
*** paste::options
*** paste::examples
*** paste::files
*** paste::see-also
** pathchk                                                                      :cmd:
[[Index][⬆]]
*** pathchk::options
*** pathchk::examples
*** pathchk::files
*** pathchk::see-also
** pinky                                                                        :cmd:
[[Index][⬆]]
*** pinky::options
*** pinky::examples
*** pinky::files
*** pinky::see-also
** pr                                                                           :cmd:
[[Index][⬆]]
*** pr::options
*** pr::examples
*** pr::files
*** pr::see-also
** printenv                                                                     :cmd:
[[Index][⬆]]
*** printenv::options
*** printenv::examples
*** printenv::files
*** printenv::see-also
** printf                                                                       :cmd:
[[Index][⬆]]
*** printf::options
*** printf::examples
*** printf::files
*** printf::see-also
** ptx                                                                          :cmd:
[[Index][⬆]]
*** ptx::options
*** ptx::examples
*** ptx::files
*** ptx::see-also
** pwd                                                                          :cmd:
[[Index][⬆]]
*** pwd::options
*** pwd::examples
*** pwd::files
*** pwd::see-also
** readlink                                                                     :cmd:
[[Index][⬆]]
*** readlink::options
*** readlink::examples
*** readlink::files
*** readlink::see-also
** realpath                                                                     :cmd:
[[Index][⬆]]
*** realpath::options
*** realpath::examples
*** realpath::files
*** realpath::see-also
** realpath                                                                     :cmd:
[[Index][⬆]]
*** realpath::options
*** realpath::examples
*** realpath::files
*** realpath::see-also
** rm                                                                           :cmd:
[[Index][⬆]] /remove files or directories
Written by Paul Rubin, David MacKenzie, Richard M. Stallman, and Jim Meyering/
*** rm::options
*** rm::examples
- rm-161118232317 :: remove all but specific file(s)
:    ~$ rm !(save_me_please.log) # just a lis of files
:    ~$ rm !(*.foo|*.bar|*.baz)  # wilde card

*** rm::files
*** rm::see-also
  unlink(1), unlink(2), chattr(1), shred(1)
** rmdir                                                                        :cmd:
[[Index][⬆]]
*** rmdir::options
*** rmdir::examples
*** rmdir::files
*** rmdir::see-also
** runcon                                                                       :cmd:
[[Index][⬆]]
*** runcon::options
*** runcon::examples
*** runcon::files
*** runcon::see-also
** seq                                                                          :cmd:
[[Index][⬆]]
*** seq::options
*** seq::examples
*** seq::files
*** seq::see-also
** sha1sum                                                                      :cmd:
[[Index][⬆]]
*** sha1sum::options
*** sha1sum::examples
*** sha1sum::files
*** sha1sum::see-also
** sha224sum                                                                    :cmd:
[[Index][⬆]]
*** sha224sum::options
*** sha224sum::examples
*** sha224sum::files
*** sha224sum::see-also
** sha256sum                                                                    :cmd:
[[Index][⬆]]
*** sha256sum::options
*** sha256sum::examples
*** sha256sum::files
*** sha256sum::see-also
** sha384sum                                                                    :cmd:
[[Index][⬆]]
*** sha384sum::options
*** sha384sum::examples
*** sha384sum::files
*** sha384sum::see-also
** sha512sum                                                                    :cmd:
[[Index][⬆]]
*** sha512sum::options
*** sha512sum::examples
*** sha512sum::files
*** sha512sum::see-also

** shred                                                                        :cmd:
[[Index][⬆]]
*** shred::options
*** shred::examples
*** shred::files
*** shred::see-also
** shuf                                                                         :cmd:
[[Index][⬆]]
*** shuf::options
*** shuf::examples
*** shuf::files
*** shuf::see-also
** sleep                                                                        :cmd:
[[Index][⬆]]
*** sleep::options
*** sleep::examples
*** sleep::files
*** sleep::see-also
** sort                                                                         :cmd:
[[Index][⬆]]
*** sort::options
*** sort::examples
*** sort::files
*** sort::see-also
** split                                                                        :cmd:
[[Index][⬆]]
*** split::options
*** split::examples
*** split::files
*** split::see-also
** stat                                                                         :cmd:
[[Index][⬆]]
*** stat::options
*** stat::examples
*** stat::files
*** stat::see-also
** stdbuf                                                                       :cmd:
[[Index][⬆]]
*** stdbuf::options
*** stdbuf::examples
*** stdbuf::files
*** stdbuf::see-also
** stty                                                                         :cmd:
[[Index][⬆]]
*** stty::options
*** stty::examples
*** stty::files
*** stty::see-also
** sum                                                                          :cmd:
[[Index][⬆]]
*** sum::options
*** sum::examples
*** sum::files
*** sum::see-also
** sync                                                                         :cmd:
[[Index][⬆]]
*** sync::options
*** sync::examples
*** sync::files
*** sync::see-also
** tac                                                                          :cmd:
[[Index][⬆]]
*** tac::options
*** tac::examples
*** tac::files
*** tac::see-also
** tail                                                                         :cmd:
[[Index][⬆]]
*** tail::options
*** tail::examples
*** tail::files
*** tail::see-also
** tee                                                                          :cmd:
[[Index][⬆]] /read from standard input and write to standard output and files/
/Written by Mike Parker, Richard M. Stallman, and David MacKenzie./

*** tee::options

You can use multiple process substitutions (works with zsh, bash, ksh)
#+BEGIN_EXAMPLE
>(COMMAND)
#+END_EXAMPLE
*** tee::examples
- tee-161115235121 :: To split pipe in multiple streams.
#+BEGIN_SRC sh
  #!/usr/bin/env bash

  echo “Command tee can split a pipe in many!” \
      |tee >(rev) \
           >(tr " " "_") \
           >(wc ) \
           >(tr "[:lower:]" "[:upper:]")
#+END_SRC
[[file:./cix-util-linux.org::*rev][rev (1)]],
[[file:./cix-gnu-core-utilities.org::*tr][tr (1)]],
[[file:./cix-gnu-bash-builtin.org::echo][echo]]

- tee-161115231840 :: Download a file and validate it on the "fly"
#+BEGIN_SRC sh
  #!/usr/bin/env bash

  # Used a real ISO image of Fedora 24 Workstation
  FILE_URL="https://download.fedoraproject.org/pub/fedora/linux/releases/24/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-24-1.2.iso"
  FILE_NAME="Fedora-Workstation-Live-x86_64-24-1.2.iso"
  CHECKSUM_URL="https://getfedora.org/en_GB/static/checksums/Fedora-Workstation-24-x86_64-CHECKSUM"
  CHECKSUM_FILE="FW24.sha245"

  wget -O - "$FILE_URL" \
       tee >(sha256sum > ./"$CHECKSUM_FILE") > "$FILE_NAME"
#+END_SRC
wget (1)
*** tee::files
*** tee::see-also
** test                                                                         :cmd:
[[Index][⬆]]
*** test::options
*** test::examples
*** test::files
*** test::see-also
** timeout                                                                      :cmd:
[[Index][⬆]]
*** timeout::options
*** timeout::examples
*** timeout::files
*** timeout::see-also
** touch                                                                        :cmd:
[[Index][⬆]]
*** touch::options
*** touch::examples
*** touch::files
*** touch::see-also
** tr                                                                           :cmd:
[[Index][⬆]] /translate or delete characters/
/Written by Jim Meyering./
*** tr::options
*** tr::examples
- tr-161120163854 :: rename files in cwd from loser to UPPER case:
#+BEGIN_SRC sh
  #!/usr/bin/env bash

  for file in ./*; do
      mv "$file" $(echo "$file" | tr '[:lower:]' '[:upper:]')
  done
#+END_SRC
[[file:./cix-gnu-bash-builtin.org::for][for]],
[[file:./cix-gnu-bash-builtin.org::*echo][echo]],
[[file:./cix-gnu-core-utilities.org::*mv][mv (1)]],
*** tr::files
*** tr::see-also
** true                                                                         :cmd:
[[Index][⬆]]
*** true::options
*** true::examples
*** true::files
*** true::see-also
** truncate                                                                     :cmd:
[[Index][⬆]]
*** truncate::options
*** truncate::examples
*** truncate::files
*** truncate::see-also
** tsort                                                                        :cmd:
[[Index][⬆]]
*** tsort::options
*** tsort::examples
*** tsort::files
*** tsort::see-also
** tty                                                                          :cmd:
[[Index][⬆]]
*** tty::options
*** tty::examples
*** tty::files
*** tty::see-also
** uname                                                                        :cmd:
[[Index][⬆]]
*** uname::options
*** uname::examples
*** uname::files
*** uname::see-also
** unexpand                                                                     :cmd:
[[Index][⬆]]
*** unexpand::options
*** unexpand::examples
*** unexpand::files
*** unexpand::see-also
** uniq                                                                         :cmd:
[[Index][⬆]]
*** uniq::options
*** uniq::examples
*** uniq::files
*** uniq::see-also
** unlink                                                                       :cmd:
[[Index][⬆]]
*** unlink::options
*** unlink::examples
*** unlink::files
*** unlink::see-also
** uptime                                                                       :cmd:
[[Index][⬆]]
*** uptime::options
*** uptime::examples
*** uptime::files
*** uptime::see-also
** users                                                                        :cmd:
[[Index][⬆]]
*** users::options
*** users::examples
*** users::files
*** users::see-also
** vdir                                                                         :cmd:
[[Index][⬆]]
*** vdir::options
*** vdir::examples
*** vdir::files
*** vdir::see-also
** wc                                                                           :cmd:
[[Index][⬆]]
*** wc::options
*** wc::examples
*** wc::files
*** wc::see-also
** who                                                                          :cmd:
[[Index][⬆]]
*** who::options
*** who::examples
*** who::files
*** who::see-also
** whoami                                                                       :cmd:
[[Index][⬆]]
*** whoami::options
*** whoami::examples
*** whoami::files
*** whoami::see-also
[[Index][⬆]]
** yes                                                                          :cmd:
[[Index][⬆]]
*** yes::options
*** yes::examples
*** yes::files
*** yes::see-also

* Reference
** Books
- Jerry Peek, Shelley Powers, Tim O'Reilly, Mike Loukides.
  *UNIX Power Tools*.
  O'reilly
- Ellen Siever, Stepben Figgins, Robert Love & Arnold Robbins;
  *Linux In a Nutshell, 6th edition*;
  O'reilly 2005;
- Stephen G. Kochan, Patrick Wood;
  *UNIX® Shell Programming, 3thd edition*;
  Sams Publishing, 2003;
** Links
- GNU Coreutils https://www.gnu.org/software/coreutils/manual/coreutils.html
- http://wiki.linuxquestions.org/
