# File           : cix-openssh.org
# Created        : <2016-11-13 Sun 19:25:52 GMT>
# Modified  : <2017-1-20 Fri 21:28:50 GMT> sharlatan
# Author         : sharlatan
# Maintainer(s)  :
# Short          :

#+OPTIONS: num:nil

[[../cix-main.org::*Index][|≣|]]
#+TITLE: OpenSSH

|--------------+---------------|
| *Author*       | Damien Miller |
| *Contributors* |               |
| *Realised*     |               |
| *Source*       |               |
| *Info*         |               |
|--------------+---------------|

SSH (Secure  SHell) is a  program for logging into  and executing commands  on a
remote machine. SSH is intended to replace *rlogin* and *rsh*, and to provide secure
encrypted  communications   between  two   untrusted  hosts  over   an  insecure
network. X11 connections  and arbitrary TCP/IP ports can also  be forwarded over
the secure channel.

OpenSSH is OpenBSD's version of the last  free version of SSH, bringing it up to
date in terms of security and features.

This package includes  the core files necessary for both  the OpenSSH client and
server. To  make this package  useful, you should also  install openssh-clients,
openssh-server, or both.

** Packages
| № | Name            | RPM | DEB | *BSD |
|---+-----------------+-----+-----+------|
| 1 | openssh-server  | +   |     |      |
| 2 | openssh-clients | +   |     |      |
|---+-----------------+-----+-----+------|

** Libraries
|  № | Name           | RPM | DEB |
|----+----------------+-----+-----|
|  1 | libaudit       |     |     |
|  2 | libc           |     |     |
|  3 | libcap-ng      |     |     |
|  4 | libcom_err     |     |     |
|  5 | libcrypt       |     |     |
|  6 | libcrypto      |     |     |
|  7 | libdl          |     |     |
|  8 | libedit        |     |     |
|  9 | libfipscheck   |     |     |
| 10 | libgssapi_krb5 |     |     |
| 11 | libk5crypto    |     |     |
| 12 | libkrb5        |     |     |
| 13 | liblber-2      |     |     |
| 14 | libpam         |     |     |
| 15 | libresolv      |     |     |
| 16 | libselinux     |     |     |
| 17 | libtinfo       |     |     |
| 18 | libutil        |     |     |
| 19 | libwrap        |     |     |
| 20 | libz           |     |     |
|----+----------------+-----+-----|
----

* Index
#+BEGIN_EXAMPLE
    scp (1)         - secure copy (remote file copy program)
    sftp (1)        - secure file transfer program
    slogin (1)      - OpenSSH SSH client (remote login program)
    ssh (1)         - OpenSSH SSH client (remote login program)
    ssh-add (1)     - adds private key identities to the authentication agent
    ssh-agent (1)   - authentication agent
    ssh-copy-id (1) - use locally available keys to authorise logins on a remote machine
    ssh-keyscan (1) - gather ssh public keys
#+END_EXAMPLE

* Receipts
** scp                                                                          :cmd:
*** scp::options
*** scp::examples
*** scp::files
*** scp::see-also
** sftp                                                                         :cmd:
*** sftp::options
*** sftp::examples
*** sftp::files
*** sftp::see-also
** slogin                                                                       :cmd:
*** slogin::options
*** slogin::examples
*** slogin::files
*** slogin::see-also
** ssh                                                                          :cmd:
*** ssh::options
*** ssh::examples
**** ssh-161211224536
revers-SOCKS-proxy
:    ~$ ssh -D 8080 -R 8080:127.0.0.1:8080 usr@1.2.3.4 ssh -R 8080:172.0.0.1:8080 user@2.3.4.5
*** ssh::files
*** ssh::see-also
** ssh-add                                                                      :cmd:
*** ssh-add::options
*** ssh-add::examples
*** ssh-add::files
*** ssh-add::see-also
** ssh-agent                                                                    :cmd:
*** ssh-agent::options
*** ssh-agent::examples
*** ssh-agent::files
*** ssh-agent::see-also
** ssh-copy-id                                                                  :cmd:
*** ssh-copy-id::options
*** ssh-copy-id::examples
*** ssh-copy-id::files
*** ssh-copy-id::see-also
** ssh-keyscan                                                                  :cmd:
*** ssh-keyscan::options
*** ssh-keyscan::examples
*** ssh-keyscan::files
*** ssh-keyscan::see-also

* References
