# File           : cix-scapy.org
# Created        : <2017-10-08 Sun 23:13:34 BST>
# Modified       : <2017-10-08 Sun 23:54:36 BST> sharlatan
# Author         : sharlatan
# Maintainer(s)  :
# Sinopsis       :

#+OPTIONS: num:nil

[[file:../README.org*Index][|≣|]]
#+TITLE: scapy
|-----------------+-------------------|
| *Author*        | Philippe Biondi   |
|                 | Guillaume Valadon |
|                 | Pierre Lalet      |
| *Maintainer(s)* |                   |
| *Released*      | 2003              |
| *Source*        | [[https://github.com/secdev/scapy][scapy.git]]         |
| *Homepage*      | [[http://www.secdev.org/projects/scapy/][scapy.weg]]         |
|-----------------+-------------------|
Scapy is a powerful Python-based interactive packet manipulation program and
library.

It is able to forge or decode packets of a wide number of protocols, send them
on the wire, capture them, match requests and replies, and much more. It
designed to allow fast packet prototyping by using default values that work.

It can easily handle most classical tasks like scanning, tracerouting, probing,
unit tests, attacks or network discovery (it can replace =hping=, 85% of =nmap̀=,
=arpspoof=, =arp-sk=, =arping=, =tcpdump=, =wireshark=, =p0f=, etc.). It also
performs very well at a lot of other specific tasks that most other tools can't
handle, like sending invalid frames, injecting your own 802.11 frames, combining
techniques (VLAN hopping+ARP cache poisoning, VoIP decoding on WEP protected
channel, ...), etc.
-----
* Index
* Receipts
* Refreances

# End of cix-scapy.org
