# File     : cix-busybox.org • spices
# Created  : <2016-11-07 Mon 21:06:33 GMT>
# Modified : <2017-9-03 Sun 21:50:16 BST> sharlatan
# Author   : #Rλatan
# Sinopsis : Statically linked binary providing simplified versions of system commands.

#+OPTIONS: num:nil

[[file:../cix-main.org][|≣|]]
#+TITLE: Busybox

|--------------+----------------|
| *Author*     | Bruce Perens   |
| *Maintainer* | Denys Vlasenko |
| *Released*   | 1999           |
| *Source*     | [[https://git.busybox.net/][busybox.git]]    |
| *Info*       | [[https://busybox.net/][busybox.web]]    |
|--------------+----------------|

BusyBox combines tiny versions of many common UNIX utilities into a single small
executable. It provides replacements for most of the utilities you usually find
in GNU fileutils, shellutils, etc. The utilities in BusyBox generally have fewer
options than their full-featured GNU cousins; however, the options that are
included provide the expected functionality and behave very much like their GNU
counterparts. BusyBox provides a fairly complete environment for any small or
embedded system.
-----
* Index
#+BEGIN_EXAMPLE
    [ () -
    [[ () -
    ar () -
    cp () -
    dc () -
    dd () -
    df () -
    du () -
    ed () -
    hd () -
    id () -
    ip () -
    ln () -
    ls () -
    mt () -
    mv () -
    nc () -
    od () -
    ps () -
    rm () -
    rx () -
    sh () -
    su () -
    sv () -
    tr () -
    vi () -
    wc () -

    arp () -
    ash () -
    awk () -
    cal () -
    cat () -
    cmp () -
    cut () -
    env () -
    lpd () -
    lpq () -
    lpr () -
    man () -
    pwd () -
    rpm () -
    sed () -
    seq () -
    sum () -
    tac () -
    tar () -
    tee () -
    top () -
    tty () -
    who () -
    yes () -

    beep () -
    catv () -
    chat () -
    chrt () -
    chvt () -
    comm () -
    cpio () -
    date () -
    diff () -
    dnsd () -
    dpkg () -
    echo () -
    expr () -
    find () -
    fold () -
    free () -
    fsck () -
    ftpd () -
    grep () -
    gzip () -
    head () -
    hush () -
    ifup () -
    init () -
    ipcs () -
    kill () -
    last () -
    less () -
    lzop () -
    mdev () -
    mesg () -
    more () -
    nice () -
    ping () -
    rdev () -
    sort () -
    stat () -
    stty () -
    sync () -
    tail () -
    test () -
    tftp () -
    time () -
    true () -
    uniq () -
    wget () -
    zcat () -
    zcip () -

    acpid () -
    blkid () -
    brctl () -
    bzcat () -
    bzip2 () -
    chgrp () -
    chmod () -
    chown () -
    chpst () -
    cksum () -
    clear () -
    crond () -
    dmesg () -
    egrep () -
    eject () -
    false () -
    fbset () -
    fdisk () -
    fgrep () -
    fsync () -
    fuser () -
    getty () -
    httpd () -
    inetd () -
    ipcrm () -
    klogd () -
    login () -
    lsmod () -
    mkdir () -
    mknod () -
    mount () -
    nohup () -
    patch () -
    pgrep () -
    pidof () -
    ping6 () -
    pkill () -
    pscan () -
    rdate () -
    reset () -
    rmdir () -
    rmmod () -
    route () -
    runsv () -
    sleep () -
    split () -
    tftpd () -
    touch () -
    uname () -
    unzip () -
    vlock () -
    watch () -
    which () -
    xargs () -

    arping () -
    chattr () -
    chroot () -
    depmod () -
    devmem () -
    envdir () -
    expand () -
    findfs () -
    ftpget () -
    ftpput () -
    getopt () -
    gunzip () -
    hdparm () -
    hostid () -
    ifdown () -
    insmod () -
    ionice () -
    ipaddr () -
    ipcalc () -
    iplink () -
    iprule () -
    length () -
    logger () -
    lsattr () -
    md5sum () -
    mkfifo () -
    mkswap () -
    mktemp () -
    nameif () -
    nmeter () -
    openvt () -
    passwd () -
    printf () -
    renice () -
    resize () -
    script () -
    setsid () -
    svlogd () -
    swapon () -
    sysctl () -
    tcpsvd () -
    telnet () -
    udhcpc () -
    udhcpd () -
    udpsvd () -
    umount () -
    unlzma () -
    unlzop () -
    uptime () -
    usleep () -
    whoami () -

    adduser () -
    bunzip2 () -
    crontab () -
    cryptpw () -
    deluser () -
    dirname () -
    fdflush () -
    hexdump () -
    hwclock () -
    ifplugd () -
    install () -
    iproute () -
    killall () -
    linux32 () -
    linux64 () -
    linuxrc () -
    logname () -
    logread () -
    losetup () -
    lzmacat () -
    lzopcat () -
    mkdosfs () -
    netstat () -
    rtcwake () -
    setarch () -
    setfont () -
    sha1sum () -
    showkey () -
    strings () -
    sulogin () -
    swapoff () -
    syslogd () -
    taskset () -
    telnetd () -
    timeout () -
    ttysize () -
    vconfig () -
    volname () -

    addgroup () -
    adjtimex () -
    basename () -
    chpasswd () -
    delgroup () -
    dos2unix () -
    dumpkmap () -
    fbsplash () -
    fdformat () -
    hostname () -
    ifconfig () -
    inotifyd () -
    iptunnel () -
    kbd_mode () -
    killall5 () -
    loadfont () -
    loadkmap () -
    makemime () -
    microcom () -
    mkpasswd () -
    modprobe () -
    nslookup () -
    printenv () -
    readlink () -
    realpath () -
    rpm2cpio () -
    runlevel () -
    runsvdir () -
    sendmail () -
    slattach () -
    unexpand () -
    unix2dos () -
    uudecode () -
    uuencode () -
    watchdog () -

    deallocvt () -
    dhcprelay () -
    envuidgid () -
    ifenslave () -
    mkfs.vfat () -
    reformime () -
    run-parts () -
    setuidgid () -
    sha256sum () -
    sha512sum () -
    softlimit () -

    dumpleases () -
    fakeidentd () -
    flash_lock () -
    fsck.minix () -
    mkfs.minix () -
    mountpoint () -
    pivot_root () -
    popmaildir () -
    setconsole () -
    setlogcons () -
    traceroute () -
    uncompress () -

    freeramdisk () -
    raidautorun () -
    readprofile () -
    setkeycodes () -
    switch_root () -

    flash_unlock () -
    scriptreplay () -

    dnsdomainname () -
    pipe_progress () -

    start-stop-daemon () -
#+END_EXAMPLE
* Referances
# End of cix-busybox.org
