# File          : cix-gnu-bash-builtin.org
# Created       : <2015-11-07 Mon 00:07:40 GMT>
# Modified      : <2017-10-13 Fri 18:51:17 BST> sharlatan
# Author        : sharlatan
# Maintainer(s) :
# Sinopsis      : The GNU Bourne Again shell

#+OPTIONS: num:nil

[[file:../cix-main.org][|≣|]]
#+TITLE: GNU Bash builtin
|-----------------+---------------------|
| *Author*        | Brian Fox,          |
|                 | Chet Ramey [[http://git.savannah.gnu.org/cgit/bash.git/tree/AUTHORS][(all...)]] |
| *Maintainer(s)* |                     |
| *Released*      | 1989                |
| *Source*        | [[http://git.savannah.gnu.org/cgit/bash.git/tree/AUTHORS][bash.git]]            |
| *Man*           |                     |
| *Info*          |                     |
|-----------------+---------------------|

The GNU Bourne Again shell (Bash) is a shell or command language interpreter
that is compatible with the Bourne shell (sh). Bash incorporates useful features
from the Korn shell (ksh) and the C shell (csh). Most sh scripts can be run by
bash without modification.
-----
* Index
** Index::Functions
#+BEGIN_EXAMPLE
    .         - Execute commands from a file in the current shell.
    [ ... ]   - Evaluate conditional expression (synonym "test").
    [[ ... ]] - Execute conditional command.
    { ... }   - Group commands as a unit.
    ( ... )   -

    bg        - Move jobs to the background.
    cd        - Change the shell working directory.
    fc        - Display or execute commands from the history list.
    fg        - Move job to the foreground.
    if        - Execute commands based on conditional.

    for       - Execute commands for each member in a list.
    let       - Evaluate arithmetic expressions.
    pwd       - Print the name of the current working directory.
    set       - Set or unset values of shell options and positional parameters.

    bind      - Set Readline key bindings and variables.
    case      - Execute commands based on pattern matching.
    dirs      - Display directory stack.
    echo      - Write arguments to the standard output.
    eval      - Execute arguments as a shell command.
    exec      - Replace the shell with the given command.
    exit      - Exit the shell.
    hash      - Remember or display program locations.
    help      - Display information about builtin commands.
    jobs      - Display status of jobs.
    kill      - Send a signal to a job.
    popd      - Remove directories from stack.
    read      - Read a line from the standard input and split it into fields.
    test      - Evaluate conditional expression.
    time      - Report time consumed by pipeline's execution.
    trap      - Trap signals and other events.
    type      - Display information about command type.
    wait      - Wait for job completion and return exit status.

    alias     - Define or display aliases.
    break     - Exit for, while, or until loops.
    false     - Return an unsuccessful result.
    local     - Define local variables.
    pushd     - Add directories to stack.
    shift     - Shift positional parameters.
    shopt     - Set and unset shell options.
    times     - Display process times.
    umask     - Display or set file mode mask.
    unset     - Unset values and attributes of shell variables and functions.
    until     - Execute commands as long as a test does not succeed.
    while     - Execute commands as long as a test succeeds.

    caller    - Return the context of the current subroutine call.
    coproc    - Create a coprocess named NAME.
    disown    - Remove jobs from current shell.
    enable    - Enable and disable shell builtins.
    export    - Set export attribute for shell variables.
    logout    - Exit a login shell.
    printf    - Formats and prints ARGUMENTS under control of the FORMAT.
    return    - Return from a shell function.
    select    - Select words from a list and execute commands.
    source    - Execute commands from a file in the current shell.
    ulimit    - Modify shell resource limits.

    builtin   - Execute shell builtins.
    command   - Execute a simple command or display information about commands.
    compgen   - Display possible completions depending on the options.
    compopt   - Modify or display completion options.
    declare   - Set variable values and attributes.
    getopts   - Parse option arguments.
    history   - Display or manipulate the history list.
    mapfile   - Read lines from the standard input into an indexed array variable.
    suspend   - Suspend shell execution.
    typeset   - Set variable values and attributes.
    unalias   - Remove each NAME from the list of defined aliases.

    complete  - Specify how arguments are to be completed by Readline.
    continue  - Resume for, while, or until loops.
    function  - Define shell function.
    readonly  - Mark shell variables as unchangeable.

    readarray - Read lines from a file into an array variable.
    variables - Common shell variable names and usage.
#+END_EXAMPLE

** Index::Variables
#+BEGIN_EXAMPLE
    BASH    - The full pathname used to execute the current instance of Bash.
    BASH_ALIASES
    BASH_ARGC
    BASH_ARGV
    BASH_CMDS
    BASH_COMMAND
    BASH_COMPAT
    BASH_ENV
    BASH_EXECUTION_STRING
    BASH_LINENO
    BASHOPTS
    BASHPID
    BASH_REMATCH
    BASH_SOURCE
    BASH_SUBSHELL
    BASH_VERSINFO
    BASH_VERSION
    BASH_XTRACEFD
    CHILD_MAX
    COLUMNS - Terminal columns number
    COMP_CWORD
    COMP_KEY
    COMP_LINE
    COMP_POINT
    COMPREPLY
    COMP_TYPE
    COMP_WORDBREAKS
    COMP_WORDS
    COPROC
    DIRSTACK
    EMACS
    ENV
    EUID
    FCEDIT
    FIGNORE
    FUNCNAME
    FUNCNEST
    GLOBIGNORE
    GROUPS
    HISTCMD
    HISTCONTROL
    HISTFILE
    HISTFILESIZE
    HISTIGNORE
    HISTSIZE
    HISTTIMEFORMAT
    HOSTFILE
    HOSTNAME
    HOSTTYPE
    IGNOREEOF
    INPUTRC
    LANG
    LINENO
    LINES
    MACHTYPE
    MAILCHECK
    MAPFILE
    OLDPWD
    OPTERR
    OSTYPE
    PIPESTATUS
    POSIXLY_CORRECT
    PPID
    PROMPT_COMMAND
    PROMPT_DIRTRIM
    PWD
    RANDOM
    READLINE_LINE
    READLINE_POINT
    REPLY
    SECONDS
    SHELL
    SHELLOPTS
    SHLVL
    TIMEFORMAT
    TMOUT
    TMPDIR
    UID
#+END_EXAMPLE
-----

* Receipts::commands

** printf

*** printf::examples

**** printf-170307215451
pirnt multiple characters:
:    ~$ printf '%0.1s' "-"{1..80}
** command                                                                      :cmd:
*** command::examples
**** command-161110202619
test wheather "CMD" installed/exists on the system:
#+BEGIN_SRC sh
  #!/usr/bin/env bash

  CMD="ls"
  command -v "$CMD" >/dev/null 2>&1 || {
      echo >&2 "$CMD is required to be installed."
      exit 1; }
#+END_SRC
[[file:./cix-gnu-core-utilities.org::*echo][echo]]
#+RESULTS:

** for                                                                          :cmd:
** history                                                                      :cmd:
*** history::examples
- history-161127235306 :: print command frequences:
  :    ~ $ history | awk '{print $2}' | sort | uniq -c | sort -nr
  :    ~ $ history | awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' | sort -rn
  [[file:./cix-gawk.org::*awk][awk (1)]], [[file:./cix-gnu-core-utilities.org::*sort][sort (1)]], [[file:./cix-gnu-core-utilities.org::*uniq][uniq (1)]]
** if                                                                           :cmd:
** read                                                                         :cmd:
** select                                                                       :cmd:
** set
*** set::examples
**** set-161224094103
list of all environment varialbes used in current session:
:    ~$ (set -o posix ; set ) | less
[[file::*less][less (1)]]

** ulimit                                                                       :cmd:
ulimit [OPTION] [SHabcdefilmnpqrstuvxT] [LIMIT]

** while                                                                        :cmd:
*** while::examples
**** while-171013184352
#+BEGIN_SRC sh
  #!/usr/bin/env bash

  _while_read()
  { # Read from a file or stdin 

      while IFS= read -r line; do
          printf "%s\n" "$line"
      done < "${1:-/dev/stdin}"
  }

  main()
  {
     _while_read "$@" 
  }

  main "$@"
  # End of script
#+END_SRC
* Receipts::variables
** PIPESTATUS

** FUNCNAME                                                                     :var:

Its a global internal variable maintained by any linux shell.  Its of type array
and consists the name of the current function from where we are trying to read
its value.  FUNCNAME is the current function name and FUNCNAME is the previous
function name and so on ... Its a stack-trace of functions executed by a shell
script.  Value of FUNCNAME gets cleared every-time we execute a new shell
script.

** IFS
use IFS to separage enteries in a string:
#+BEGIN_SRC sh
#!/usr/bin/env bash

SYS_USRS="
    usr1:hash-1:1003:/home/user1:/bin/bash:group1,gropu2
    usr2:hash-2:1004:/home/user2:/bin/bash:group3,group4
    usr3:hash-3:1005:/home/user3:/bin/bash:group5,group6
"

sys_cfg_usrs() { # Add/mod system users
    local usr hash gid home shell

    for usr_str in $SYS_USRS; do
        IFS=: read usr hash uid home shell groups <<< "$usr_str"

        if id "$usr" &>/dev/null; then
            echo "Modifing"
            usermod -d "$home" \
                    -u "$uid" \
                    -G "$groups" \
                    -p "$hash" \
                    -s "$shell" \
                    "$usr"
        else
            echo "Adding"
            useradd -d "$home" \
                    -u "$uid" \
                    -G "$groups" \
                    -p "$hash" \
                    -s "$shell" \
                    "$usr"
        fi
    done
}

main() {
    sys_cfg_usrs
    echo "$IFS"
}

main "$@"
#+END_SRC
* Referance
** Links
- Bash Variables
  https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html
- Bash Guide
  http://mywiki.wooledge.org/BashGuide
- Index of Shell Builtin Commands
  https://www.gnu.org/software/bash/manual/html_node/Builtin-Index.html#Builtin-Index
- Environment Variables
  http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08
- Bash oneliners
  http://www.bashoneliners.com/
** Hubs
- https://github.com/awesome-lists/awesome-bash

# End of cix-gnu-bash.org
