# File           : cix-vim.org
# Created        : <2017-08-07 Mon 00:28:12 BST>
# Modified       : <2017-12-18 Mon 01:21:40 GMT> Sharlatan
# Author         : sharlatan
# Maintainer(s)  :
# Sinopsis       : Vim is a greatly improved version of the good old UNIX editor Vi

#+OPTIONS: num:nil

[[file:../cix-main.org][|≣|]]
#+TITLE: vim
|---------------+----------------|
| *Author*      | Bram Moolenaar |
| *Contibutors* |                |
| *Released*    | 1991           |
| *Source*      | [[https://github.com/vim/vim][vim.git]]        |
| *Homepage*    | [[http://www.vim.org/vim.web][vim.web]]        |
|---------------+----------------|
VIM (VIsual editor iMproved) is an updated and improved version of the vi
editor. Vi was the first real screen-based editor for UNIX, and is still very
popular. VIM improves on vi by adding new features: multiple windows,
multi-level undo, block highlighting and more. The vim-enhanced package contains
a version of VIM with extra, recently introduced features like Python and Perl
interpreters.

Install the vim-enhanced package if you'd like to use a version of the VIM
editor which includes recently added enhancements like interpreters for the
Python and Perl scripting languages. You'll also need to install the vim-common
package.
** Packages
vim-enhanced
-----
* Index
* Receipts
* Refreances
- Best of Vim Tips
  https://www.zinkwazi.com/unix/notes/vimtips.html
# End of cix-vim.org
