# File           : cix-openssh.org
# Created        : <2016-11-13 Sun 19:25:52 GMT>
# Last Modified  : <2016-11-14 Mon 22:13:37 GMT> sharlatan
# Author         : sharlatan
# Maintainer(s)  :
# Short          :

#+OPTIONS: num:nil


#+TITLE: OpenSSH

| Author |
|        |

SSH (Secure  SHell) is a  program for logging into  and executing commands  on a
remote machine. SSH is intended to replace *rlogin* and *rsh*, and to provide secure
encrypted  communications   between  two   untrusted  hosts  over   an  insecure
network. X11 connections  and arbitrary TCP/IP ports can also  be forwarded over
the secure channel.

OpenSSH is OpenBSD's version of the last  free version of SSH, bringing it up to
date in terms of security and features.

This package includes  the core files necessary for both  the OpenSSH client and
server. To  make this package  useful, you should also  install openssh-clients,
openssh-server, or both.

----

** Index
#+BEGIN_EXAMPLE
scp (1)              - secure copy (remote file copy program)
sftp (1)             - secure file transfer program
slogin (1)           - OpenSSH SSH client (remote login program)
ssh (1)              - OpenSSH SSH client (remote login program)
ssh-add (1)          - adds private key identities to the authentication agent
ssh-agent (1)        - authentication agent
ssh-copy-id (1)      - use locally available keys to authorise logins on a remote machine
ssh-keyscan (1)      - gather ssh public keys
#+END_EXAMPLE
** Receipts

** References
