# File          : cix-glibc-common.org
# Created       : <2016-11-14 Mon 21:40:36 GMT>
# Modified      : <2018-7-05 Thu 21:59:55 BST> Sharlatan
# Author        : sharlatan
# Maintainer(s) :
# Sinopsis      : <The GNU C library>

#+OPTIONS: num:nil

[[file:../cix-main.org][|≣|]]
#+TITLE: GNU C Library
|                |                |
|----------------+----------------|
| *Author*       | Roland McGrath |
| *Contributors* | [[https://sourceware.org/glibc/wiki/MAINTAINERS][(all...)]]       |
| *Released*     | 1987           |
| *Source*       | [[git://sourceware.org/git/glibc.git][glibc.git]]      |
| *Homepage*     | [[https://www.gnu.org/software/libc/][glibc.web]]      |
|----------------+----------------|

The glibc package contains standard libraries which are used by multiple
programs on the system. In order to save disk space and memory, as well as to
make upgrading easier, common system code is kept in one place and shared
between programs. This particular package contains the most important sets of
shared libraries: the standard C library and the standard math library. Without
these two libraries, a Linux system will not function.
-----

** Packages
glibc
glibc-common
glibc-benchtests
glibc-devel
glibc-utils
glibc-static
glibc-headers
* Index
#+BEGIN_EXAMPLE
    memusage (1)     - profile memory usage of a program
    memusagestat (1) - generate graphic from memory profiling data
    mtrace (3)       - malloc tracing
    mtrace (1)       - interpret the malloc trace log
    zic (8)          - timezone compiler
    ldd (1)          - print shared library dependencies
    pldd (1)         - display dynamic shared objects linked into a process
    sprof (1)        - read and display shared object profiling data
    encat (1p)       - generate a formatted message catalog
    zdump (8)        - timezone dumper
    iconv (3)        - perform character set conversion
    iconv (1)        - convert text from one character encoding to another
    iconv (3p)       - codeset conversion function
    iconv (1p)       - codeset conversion
    getent (1)       - get entries from Name Service Switch libraries
    locale (3pm)     - Perl pragma to use or avoid POSIX locales for built-in operations
    locale (7)       - description of multilanguage support
    locale (1)       - get locale-specific information
    locale (5)       - describes a locale definition file
    locale (1p)      - get locale-specific information
    getconf (1p)     - get configuration values
    tzselect (8)     - select a timezone
    localedef (1)    - compile locale definition files
    localedef (1p)   - define locale environment
    ldconfig (8)     - configure dynamic linker run-time bindings
    sln (8)          - create symbolic links
    iconvconfig (8)  - create iconv module configuration cache
#+END_EXAMPLE
* Receipts
** zic                                                                          :cmd:
*** zic::options
*** zic::examples
*** zic::files
*** zic::see-also
** ldd                                                                          :cmd:
*** ldd::options
*** ldd::examples
**** ldd-170712005358
Find most used libraries on your system:
#+BEGIN_SRC sh
  #!/usr/bin/env bash

  find /usr/bin -type f -executable -exec sh -c "file -i '{}' \
       | grep -q 'x-executable; charset=binary'" \; -print \

#+END_SRC

#+RESULTS:

*** ldd::files
*** ldd::see-also
** pldd                                                                         :cmd:
*** pldd::options
*** pldd::examples
*** pldd::files
*** pldd::see-also
** sprof                                                                        :cmd:
*** sprof::options
*** sprof::examples
*** sprof::files
*** sprof::see-also
** encat                                                                        :cmd:
*** encat::options
*** encat::examples
*** encat::files
*** encat::see-also
** zdump                                                                        :cmd:
*** zdump::options
*** zdump::examples
*** zdump::files
*** zdump::see-also
** iconv                                                                        :cmd:
*** iconv::options
*** iconv::examples
*** iconv::files
*** iconv::see-also
** getent                                                                       :cmd:
*** getent::options
*** getent::examples
*** getent::files
*** getent::see-also
** locale                                                                       :cmd:
*** locale::options
*** locale::examples
*** locale::files
*** locale::see-also
** getconf                                                                      :cmd:
*** getconf::options
*** getconf::examples
*** getconf::files
*** getconf::see-also
** tzselect                                                                     :cmd:
*** tzselect::options
*** tzselect::examples
*** tzselect::files
*** tzselect::see-also
** localedef                                                                    :cmd:
*** localedef::options
*** localedef::examples
*** localedef::files
*** localedef::see-also
** localedef                                                                    :cmd:
*** localedef::options
*** localedef::examples
*** localedef::files
*** localedef::see-also
* References

# End of cix-glibc.org
