# File          : gnu-core-utilities.md
# Created       : Wed 14 Oct 2015 23:07:41
# Last Modified : Fri 14 Oct 2016 22:03:30 sharlatan
# Maintainer    : sharlatan

[[../README.md#Index "Index"][|≣|]][[https://www.gnu.org/software/coreutils/coreutils.html][↷|]]
- <<⬆>>

#+TITLE: GNU core utilities

|-------------+---------------|
| *Author*      |               |
|-------------+---------------|
| *Maintainers* |               |
| *Realised*    |               |
| *Source*      | [[http://git.savannah.gnu.org/cgit/coreutils.git][coreutils.git]] |
| *Info*        | [[http://www.gnu.org/software/coreutils/manual/coreutils.html][GNU Coreutils]] |
|-------------+---------------|

The GNU Core Utilities are the basic file, shell and text manipulation
utilities of the  GNU operating system.  These are  the core utilities
which are expected  to exist on every operating  system.  This package
is the union of the GNU fileutils, sh-utils, and textutils packages.

* Installation

This package is installed on most  of Linux distributions but in case
of missing you can install it manually

** Linux
*** rpm
RedHat, CentOS, Fedora, Scientific Linux

#+BEGIN_EXAMPLE
    $: yum [dnf] search coreutils
    $: sudo yum install coreutils
#+END_EXAMPLE

*** deb
Debian, Ubuntu, Linux Mint

#+BEGIN_EXAMPLE
    $: sudo apt-get install coreutils
#+END_EXAMPLE

-----

* Commands
#+BEGIN_EXAMPLE
    cp (1)        - copy files and directories
    dd (1)        - convert and copy a file
    df (1)        - report file system disk space usage
    du (1)        - estimate file space usage
    id (1)        - print real and effective user and group IDs
    ln (1)        - make links between files
    ls (1)        - list directory contents
    mv (1)        - move (rename) files
    nl (1)        - number lines of files
    od (1)        - dump files in octal and other formats
    pr (1)        - convert text files for printing
    rm (1)        - remove files or directories
    tr (1)        - translate or delete characters
    wc (1)        - print newline, word, and byte counts for each file

    cat (1)       - concatenate files and print on the standard output
    cut (1)       - remove sections from each line of files
    dir (1)       - list directory contents
    env (1)       - run a program in a modified environment
    fmt (1)       - simple optimal text formatter
    ptx (1)       - produce a permuted index of file contents
    pwd (1)       - print name of current/working directory
    seq (1)       - print a sequence of numbers
    sum (1)       - checksum and count the blocks in a file
    tac (1)       - concatenate and print files in reverse
    tee (1)       - read from standard input and write to standard output and files
    tty (1)       - print the file name of the terminal connected to standard input
    who (1)       - show who is logged on
    yes (1)       - output a string repeatedly until killed

    arch (1)      - print machine hardware name (same as uname - m)
    comm (1)      - compare two sorted files line by line
    date (1)      - print or set the system date and time
    echo (1)      - display a line of text
    expr (1)      - evaluate expressions
    fold (1)      - wrap each input line to fit in specified width
    head (1)      - output the first part of files
    join (1)      - join lines of two files on a common field
    link (1)      - call the link function to create a link to a file
    nice (1)      - run a program with modified scheduling priority
    shuf (1)      - generate random permutations
    sort (1)      - sort lines of text files
    stat (1)      - display file or file system status
    stty (1)      - change and print terminal line settings
    sync (1)      - flush file system buffers
    tail (1)      - output the last part of files
    test (1)      - check file types and compare values
    true (1)      - do nothing, successfully
    uniq (1)      - report or omit repeated lines
    vdir (1)      - list directory contents

    chcon (1)     - change file SELinux security context
    chgrp (1)     - change group ownership
    chmod (1)     - change file mode bits
    chown (1)     - change file owner and group
    cksum (1)     - checksum and count the bytes in a file
    false (1)     - do nothing, unsuccessfully
    mkdir (1)     - make directories
    mknod (1)     - make block or character special files
    nohup (1)     - run a command immune to hangups, with output to a non-tty
    nproc (1)     - print the number of processing units available
    paste (1)     - merge lines of files
    pinky (1)     - lightweight finger
    rmdir (1)     - remove empty directories
    shred (1)     - overwrite a file to hide its contents, and optionally delete it
    sleep (1)     - delay for a specified amount of time
    split (1)     - split a file into pieces
    touch (1)     - change file timestamps
    tsort (1)     - perform topological sort
    uname (1)     - print system information
    users (1)     - print the user names of users currently logged in to the current host

    base64 (1)    - base64 encode/decode data and print to standard output
    chroot (1)    - run command or interactive shell with special root directory
    csplit (1)    - split a file into sections determined by context lines
    expand (1)    - convert tabs to spaces
    factor (1)    - factor numbers
    groups (1)    - print the groups a user is in
    hostid (1)    - print the numeric identifier for the current host
    md5sum (1)    - compute and check MD5 message digest
    mkfifo (1)    - make FIFOs (named pipes)
    mktemp (1)    - create a temporary file or directory
    numfmt (1)    - Convert numbers from/to huma-readable strings
    printf (1)    - format and print data
    runcon (1)    - run command with specified SELinux security context
    stdbuf (1)    - Run COMMAND, with modified buffering operations for its standard streams.
    unlink (1)    - call the unlink function to remove the specified file
    uptime (1)    - Tell how long the system has been running.
    whoami (1)    - print effective userid

    dirname (1)   - strip last component from file name
    install (1)   - copy files and set attributes
    logname (1)   - print user's login name
    pathchk (1)   - check whether file names are valid or portable
    sha1sum (1)   - compute and check SHA1 message digest
    timeout (1)   - run a command with a time limit

    basename (1)  - strip directory and suffix from filenames
    printenv (1)  - print all or part of environment
    readlink (1)  - print resolved symbolic links or canonical file names
    realpath (1)  - print the resolved path
    realpath (3)  - return the canonicalized absolute pathname
    truncate (1)  - shrink or extend the size of a file to the specified size
    unexpand (1)  - convert spaces to tabs

    dircolors (1) - color setup for ls
    sha224sum (1) - compute and check SHA224 message digest
    sha256sum (1) - compute and check SHA256 message digest
    sha384sum (1) - compute and check SHA384 message digest
    sha512sum (1) - compute and check SHA512 message digest
#+END_EXAMPLE
-----

[[⬆]]
** dd

Test NFS/LAN speed

    $: time dd if=/dev/zer of=/<mount_of_your_nfs_dir>/testfile bs=16k count=16384

After creating 256Mb file on your remote server, read it back

    $: time dd if=/<mount_of_your_nfs_dir>/tesfile of=/dev/null bs=16k

[[⬆]](#top)
** ls
: ls [-aAlbBCdDfFghHiIklLmNopqQrRsStTuvwxXZ1] [FILE/DIRECTORY]

Sweet examples of using *ls*
#+BEGIN_EXAMPLE
    $: ls -Rotti
    $: ls -Ham
    $: ls -and
    $: ls -alSh
#+END_EXAMPLE

List only: Dir, files, links;  hidden dirs, hidden files hidden links,
exec files. Actively using -F key to classify */=>@|
#+BEGIN_EXAMPLE
    $: ls -F | grep '/' | cut -d/ -f1
    $: ls -p | grep -v /
    $: ls -F | grep '[@]' | cut -d@ -f1
#+END_EXAMPLE

Aliases best practice.
#+BEGIN_EXAMPLE
    alias ls="ls -1p --color=auto"
    alias l="ls -lhGgo"
    alias ll="ls -lh"
    alias la="ls -lhGgoA"
    alias lt="ls -lhGgotr"
    alias lS="ls -lhGgoSr"
    alias l.="ls -lhGgod .*"
    alias lhead="ls -lhGgo | head"
    alias ltail="ls -lhGgo | tail"
    alias lmore='ls -lhGgo | more'
#+END_EXAMPLE

[[⬆]](#top)
** tr
: tr [-cdstdts]... SET1 [SET2]

"convert" Mac ASCII file to UNIX.

    tr '\015' '\012' < file.mac > file.UNIX

Change uppercase to lowercase in a file:

    cat file | tr 'A-Z' 'a-z'

Turn spaces into newlines:

    tr ' ' '\012' < file


------
[[⬆]](#top)
* Reference
- Jerry Peek, Shelley Powers, Tim O'Reilly, Mike Loukides. *UNIX Power Tools*. O'reilly
- Ellen Siever, Stepben Figgins, Robert Love & Arnold Robbins. *Linux In a Nutshell*. O'reilly
